name: SynapseOS TEST

# Контроль событий при которых будет сборка
on:
  schedule: # Минута   Час        День       Месяц      День недели
    - cron:   '0        12        *           *         *'

  workflow_dispatch:

# Выполнение рабочего процесса состоит из одного или нескольких заданий, которые могут выполняться последовательно или параллельно
jobs:
  build:
    #  Все будет работать на последней версии Ubuntu
    runs-on: ubuntu-latest

    # Шаги представляют собой последовательность задач, которые будут выполняться как часть задания
    steps:
      - uses: actions/checkout@v3

      # 123
      - name: 123
        run: |
          echo 123