name: SynapseOS Buildbot

# Контроль событий при которых будет сборка
on:
  # В нашем случае это push в ветку master
  push:
    tags:
        - "v*"
    branches: [ "master" ]
  #pull_request:
  #  tags:
  #      - "v*"
  #  branches: [ "master" ]
  # Позволяет запускать этот рабочий процесс вручную на вкладке Actions
  workflow_dispatch:

# Выполнение рабочего процесса состоит из одного или нескольких заданий, которые могут выполняться последовательно или параллельно
jobs:
  build:
    #  Все будет работать на последней версии Ubuntu
    runs-on: ubuntu-latest

    # Шаги представляют собой последовательность задач, которые будут выполняться как часть задания
    steps:
      - uses: actions/checkout@v3

      # Установка зависимостей
      - name: Установка зависимостей
        run: |
          sudo apt install python3 build-essential xorriso grub-pc-bin mtools fasm zip doxygen
          wget -nv https://github.com/lordmilko/i686-elf-tools/releases/download/7.1.0/i686-elf-tools-linux.zip
          sudo unzip i686-elf-tools-linux.zip -d /usr/local
          rm i686-elf-tools-linux.zip
          
      # Запуск сборки ядра
      - name: Сборка ядра
        run: python3 scripts/build.py kernel

      # Создание дистрибутива (ISO)
      - name: Создание дистрибутива (ISO)
        run: python3 scripts/build.py iso_l
      
      # Генерация документации
      - name: Генерация документации
        run: |
          python3 scripts/build.py docs
          tar -cvf doxygen.tar.gz doxygen/
          ls
      # Проверка релиза
      - name: Проверка релиза
        run: |
          echo "done!"
          ls isodir/boot/
          ls
        
      # Публикация документации
      #- name: Commit changes
      #  uses: EndBug/add-and-commit@v9
      #  with:
      #    author_name: Github
      #    author_email: github@example.com
      #    message: 'документация: Обновление документации с помощью doxygen [Автосборка]'
      #    add: 'docs/doxygen/html/*'

      # Публикация релиза
      - name: Публикация релиза
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GIT_TOKEN }}"
          automatic_release_tag: "latest-unstable"
          prerelease: true
          title: "[Автосборка] Нестабильный релиз"
          description: "Внимание! Данный релиз собран из последних изменений в ядре! Это не окончательная версия содержит ошибки и не рекомендуется к запуску без проверки на виртуальной машине."
          files: |
            LICENSE
            SynapseOS-grub.iso
            SynapseOS-limine.iso
            isodir/boot/kernel.elf
            doxygen/rtf/refman.rtf
            doxygen.tar.gz
