name: push

# Контроль событий при которых будет сборка
on:
  # В нашем случае это push в ветку master
  push:
    tags:
        - "v*"
    branches: [ "main" ]
  #pull_request:
  #  tags:
  #      - "v*"
  #  branches: [ "master" ]
  # Позволяет запускать этот рабочий процесс вручную на вкладке Actions
  workflow_dispatch:

# Выполнение рабочего процесса состоит из одного или нескольких заданий, которые могут выполняться последовательно или параллельно
jobs:
  build:
    #  Все будет работать на последней версии Ubuntu
    runs-on: ubuntu-latest

    # Шаги представляют собой последовательность задач, которые будут выполняться как часть задания
    steps:
      - uses: actions/checkout@v3

      # Установка зависимостей
      - name: Установка зависимостей
        run: |
          sudo apt install python3 build-essential xorriso grub-pc-bin mtools zip cmake make
          wget -nv https://github.com/lordmilko/i686-elf-tools/releases/download/7.1.0/i686-elf-tools-linux.zip
          sudo unzip i686-elf-tools-linux.zip -d /usr/local
          rm i686-elf-tools-linux.zip

      # Сборка doxygen
      - name: Сборка doxygen
        run: |
          wget https://www.doxygen.nl/files/doxygen-1.9.5.linux.bin.tar.gz
          tar -xzf  doxygen-1.9.5.linux.bin.tar.gz>null
          cd doxygen-1.9.5/
          sudo make install
          cd ..
          
      # Запуск сборки ядра
      - name: Сборка ядра
        run: python3 scripts/build.py kernel

      # Создание дистрибутива (ISO)
      - name: Создание дистрибутива (ISO)
        run: |
          git clone https://github.com/limine-bootloader/limine.git --branch=v3.0-branch-binary --depth=1
          make -C limine
          ls limine
          xorriso -as mkisofs -b limine-cd.bin -no-emul-boot -boot-load-size 4 -boot-info-table --efi-boot limine-cd-efi.bin -efi-boot-part --efi-boot-image --protective-msdos-label isodir -o SynapseOS-limine.iso
          grub-mkrescue -o SynapseOS-grub.iso isodir

      # Генерация документации
      - name: Генерация документации
        run: |
          echo mkdir -p doxygen
          mkdir -p doxygen

          echo ls
          ls

          echo ls scripts/
          ls scripts/

          echo ls scripts/doxygen
          ls scripts/doxygen

          echo ls scripts/doxygen/doxygen-awesome-css
          ls scripts/doxygen/doxygen-awesome-css

          echo doxygen scripts/Doxyfile
          doxygen scripts/Doxyfile

          echo tar -cf doxygen.tar.gz doxygen/
          tar -cf doxygen.tar.gz doxygen/

          echo ls
          ls
        
      # Проверка релиза
      - name: Проверка релиза
        run: |
          echo "           /"
          ls
          echo "           isodir/boot/"
          ls isodir/boot/
          pip3 install aiogram
        continue-on-error: true
          
        # Отправка в телеграм
      - name: Отправка релиза админам
        env:
          TG_TEXT: ${{ secrets.TELEGRAM_TOKEN }}
          TG_KEY: ${{ secrets.TELEGRAM_TOKEN }}
        run: python3 scripts/send_admin.py "$TG_KEY" PUSH
        continue-on-error: true

        
      # Публикация документации
      #- name: Commit changes
      #  uses: EndBug/add-and-commit@v9
      #  with:
      #    author_name: Github
      #    author_email: github@example.com
      #    message: 'документация: Обновление документации с помощью doxygen [Автосборка]'
      #    add: 'docs/doxygen/html/*'

      # Публикация релиза
      - name: Публикация релиза
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GIT_TOKEN }}"
          automatic_release_tag: "latest-unstable"
          prerelease: true
          title: "[Автосборка] Нестабильный релиз"
          description: "Внимание! Данный релиз собран из последних изменений в ядре! Это не окончательная версия содержит ошибки и не рекомендуется к запуску без проверки на виртуальной машине."
          files: |
            LICENSE
            SynapseOS-grub.iso
            SynapseOS-limine.iso
            isodir/boot/kernel.elf
            doxygen/rtf/refman.rtf
            doxygen.tar.gz
