name: test

# Контроль событий при которых будет сборка
on:
  #pull_request:
  #  tags:
  #      - "v*"
  #  branches: [ "master" ]
  # Позволяет запускать этот рабочий процесс вручную на вкладке Actions
  workflow_dispatch:

# Выполнение рабочего процесса состоит из одного или нескольких заданий, которые могут выполняться последовательно или параллельно
jobs:
  build:
    #  Все будет работать на последней версии Ubuntu
    runs-on: ubuntu-latest

    # Шаги представляют собой последовательность задач, которые будут выполняться как часть задания
    steps:
      - uses: actions/checkout@v3
          
        # Отправка в телеграм
      - name: Проверка env
        run: echo  $TG_TEXT

      # Установка зависимостей
      - name: Установка зависимостей
        run: |
          sudo apt install python3 doxygen
          
      # Генерация документации
      - name: Генерация документации
        run: |
          mkdir -p doxygen
          doxygen scripts/Doxyfile
          tar -cvf doxygen.tar.gz doxygen/
          ls
        
      # Проверка релиза
      - name: Проверка релиза
        run: |
          pip3 install aiogram
        continue-on-error: true
          
        # Отправка в телеграм
      - name: Отправка релиза админам
        env:
          TG_TEXT: ${{ secrets.TELEGRAM_TOKEN }}
          TG_KEY: ${{ secrets.TELEGRAM_TOKEN }}
        run: python3 scripts/send_admin.py "$TG_KEY" PUSH
        continue-on-error: true
          
